var s = Ext.create('Ext.data.Store', {
	storeId: 'lectureStore',
//	model: 'app.model.Lecture',
	fields: ['title'],
	data: [
		{ "title": "Lect" },
		{ "title": "Lect 2" },
		{ "title": "Lect" },
		{ "title": "Lect 2" },
		{ "title": "Lect" },
		{ "title": "Lect 2" },
		{ "title": "Lect" },
		{ "title": "Lect 2" },
		{ "title": "Lect" },
		{ "title": "Lect 2" },
		{ "title": "Lect" },
		{ "title": "Lect 2" },
		{ "title": "Lect" },
		{ "title": "Lect 2" },
		{ "title": "Lect" },
		{ "title": "Lect 2" },
		{ "title": "Lect" },
		{ "title": "Lect" },
		{ "title": "Lect 2" },
		{ "title": "Lect" },
		{ "title": "Lect 2" },
		{ "title": "Lect" },
		{ "title": "Lect 2" },
		{ "title": "Lect" },
		{ "title": "Lect 2" },
		{ "title": "Lect" },
		{ "title": "Lect 2" },
		{ "title": "Lect" },
		{ "title": "Lect 2" },
		{ "title": "Lect" },
		{ "title": "Lect 2" },
		{ "title": "Lect" },
		{ "title": "Lect 2" },
		{ "title": "Lect" },
		{ "title": "Lect" },
		{ "title": "Lect 2" },
		{ "title": "Lect" },
		{ "title": "Lect 2" },
		{ "title": "Lect" },
		{ "title": "Lect 2" },
		{ "title": "Lect" },
		{ "title": "Lect 2" },
		{ "title": "Lect" },
		{ "title": "Lect 2" },
		{ "title": "Lect" },
		{ "title": "Lect 2" },
		{ "title": "Lect" },
		{ "title": "Lect 2" },
		{ "title": "Lect" },
		{ "title": "Lect 2" },
		{ "title": "Lect" },
		{ "title": "Lect 2" },
		{ "title": "Lect 3" }
	],
	autoLoad: false
})

//s.load(function(){
//	alert(s.first().getTitle());
//});
