var COMP_MAIN_MENU;
var COMP_TAB_SCHEDULE, COMP_TAB_CONTACT, COMP_TAB_EVENTS, COMP_TAB_SPONSORS;
var COMP_SCHEDULE_LIST, COMP_SCHEDULE_DETAILS, COMP_SCHEDULE_DETAILS_CONTENT;
var COMP_EVENTS_LIST, COMP_EVENTS_DETAILS, COMP_EVENTS_DETAILS_CONTENT;
var COMP_SPONSORS_LIST, COMP_SPONSORS_DETAILS, 
    COMP_SPONSORS_DETAILS_MENU, 
    COMP_SPONSORS_DETAILS_INFO_HEADER, COMP_SPONSORS_DETAILS_EVENTS_HEADER, COMP_SPONSORS_DETAILS_VACANCIES_HEADER, 
    COMP_SPONSORS_DETAILS_INFO, COMP_SPONSORS_DETAILS_INFO_CONTENT,
    COMP_SPONSORS_DETAILS_EVENTS, COMP_SPONSORS_DETAILS_EVENTS_CONTENT,
    COMP_SPONSORS_DETAILS_VACANCIES, COMP_SPONSORS_DETAILS_VACANCIES_CONTENT;

function init_components(){
  init_schedule_components();
  init_contact_components();
  init_events_components();
  init_sponsor_components();
}
